const placenames = [
    ["Tynwald", "Assembly Field (þingvöllr)"],
    ["Ballasalla", "Farm of/by/in the willow trees"],
    ["Burroo", "Hill, mound (borg)"],
    ["Douglas", "Deep/Black River (Dubhghlais)"],
    ["Jurby", "Deer settlement/animal farm (djura-by)"],
    ["Laxey", "Salmon river (Lax-a)"],
    ["Sky Hill", "Low cape mountain (Skaga-fjall)"],
    ["Langness", "Long promontory (langa-nes)"],
    ["Crossag", "Little crossing place"],
    ["Groudle", "narrow glen (grafdalr)"],
    ["Snaefell", "snow mountain (snjae-fjall)"],
    ["Ronaldsway", "Rognvald’s ford/crossing (Rognalds-uad)"],
    ["Emblem", null],
    ["Knock y Doonee", "Hill of the Church"],
    ["Balladoole", "Doole’s farm (Norse name Dugald)"],
    ["Ramsey", "Garlic river (hrams-a)"],
    ["Cregneash", "Crooked promontory (krok-nes)"],
    ["Cornaa", "Mill river (kuern-a)"],
    ["Rushen", "moor, heath, wood (roisean)"],
    ["Ballabeg", "Little farm"],
    ["Balley Chashtal", "Castletown"],
    ["Peel", "pele (fortification, palisade)"],
    ["Port Erin", "Irish port"],
    ["Sulby", "farm by the cleft fork in the river (sula-by)"],
    ["Hango Hill", "hanga-haugr, Gallows hill"]
];